hpc <- read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors = FALSE, na.strings= "?")
hpcsub <- subset(hpc, (hpc$Date == "1/2/2007" | hpc$Date== "2/2/2007"))
png(file="plot1.png", width=480, height=480)
hist(hpcsub$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global active power (kilowatts)")
dev.off()