hpc <- read.table("household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors = FALSE, na.strings= "?") 
hpcsub <- subset(hpc, (hpc$Date == "1/2/2007" | hpc$Date== "2/2/2007"))
hpcsub$Date <- as.Date(hpcsub$Date, "%d/%m/%Y")
hpcsub$DateTime <- paste(hpcsub$Date, hpcsub$Time, sep = " ")
hpcsub$DateTime <- strptime(hpcsub$DateTime, "%Y-%m-%d %H:%M:%S") 
png(file="plot2.png", width=480, height=480)
plot(hpcsub$DateTime, hpcsub$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab=" ")
dev.off()